remote_theme: "mmistakes/minimal-mistakes"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Ivan Lin — Networking Blog]
description: [Networking Fundamentals, Engineering, Automation, and Research]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache