remote_theme: "mmistakes/minimal-mistakes"

title: "Ivan Lin — Networking Blog"
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache